framework:
    workflows:
        eventStatus:
            #nom du workflow : eventStatus
            type: 'state_machine'
            #                le state_machine est dit cyclique, c’est-à-dire que notre objet peut revenir dans un état qu’il a déjà connu, ce que ne peut pas faire un workflow
            marking_store:
                #                Ensuite, nous avons défini avec l’option marking_store la manière dont nous voulons stocker l’état
                #                actuel de notre objet. Ici, cela veut simplement dire que nous allons stocker l’état dans un attribut state de notre objet en utilisant une méthode setState.
                type: 'single_state'
                arguments:
                    - 'state'
#                    - 'status'

            supports:
                - App\Entity\Event
            initial_place: EnCreation # état de départ de notre objet.
            places:
                - EnCreation
                - Ouverte
                - Cloturee
                - ActiviteEnCours
                - Passee
                - Annulee
            transitions:
                newEvent:
                    from: EnCreation
                    to: EnCreation
                eventPublish:
                    from: EnCreation
                    to: Ouverte
                eventClose:
                    from: Ouverte
                    to: Cloturee
                eventNow:
                    from: Ouverte
                    to: ActiviteEnCours
                eventPast:
                    from: Cloturee
                    to: Passee
                cancelEvent:
                    from: [EnCreation, Ouverte]
                    to: Annulee


